name: Testim Manual Trigger

on:
  workflow_dispatch:
    inputs:
      testim-base-url: 
        description: provide base URL for the test cases
        required: false
        type: string
        default: https://demo.openlane.dev
      testim-branch: 
        description: specify branch to be executed
        required: true
        type: string
        default: ginnExecution
      testim-group-type: 
        description: specify test group type in Testim
        required: false
        type: string
        default: label
      testim-asset-name: 
        description: label name, suite name or test plan name
        required: true
        type: string
        default: Demo BLC Login

jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli

      - name: Run Testim Smoke Tests
        run: |
          echo "Running Testim Smoke Tests..."
          testim --token ${{ secrets.TESTIMWEBTOKEN }} \
                 --project "c8ylu6OetLu3Ovnm7RLA" \
                 --grid "Testim-Grid" \
                 --mode "selenium" \
                 --branch "${{ github.event.inputs.testim-branch }}" \
                 --${{ github.event.inputs.testim-group-type }} "${{ github.event.inputs.testim-asset-name }}" \
                 --base-url "${{ github.event.inputs.testim-base-url }}"  \
                 --parallel 1 \
                 --timeout 1200000 \
                 --report-file ./results.xml
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: testim-results
          path: ./testim-results.xml